version: '3.8'
services:
  backend:
    build:
      context: ./
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-tier

  mysqldb:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - 'mysqldb-data:/var/lib/mysql'
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge