version: '3.8'
services:
  backend:
    build:
      context: ./
    volumes:
      - .:/app  # 현재 디렉토리를 /app으로 마운트
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-tier

  mysqldb:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - 'mysqldb-data:/var/lib/mysql'
    networks:
      - app-tier

#  phpmyadmin:
#    image: phpmyadmin
#    restart: always
#    ports:
#      - 80:80
#    environment:
#      PMA_ARBITRARY: 1
#      PMA_HOST: mysqldb
#      PMA_PORT: 3306
#    networks:
#      - app-tier

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#    ports:
#      - '9200:9200'
#      - '9300:9300'
#    networks:
#      - app-tier
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.10.1
#    container_name: kibana
#    depends_on:
#      - elasticsearch
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - '5601:5601'
#    networks:
#      - app-tier
#
#  filebeat:
#    image: docker.elastic.co/beats/filebeat:8.10.1
#    container_name: filebeat
#    user: root
#    volumes:
#      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro  # Filebeat 설정 파일
#      - ./logs:/var/log                                     # 로그 파일 경로
#    depends_on:
#      - elasticsearch
#    networks:
#      - app-tier
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.10.1
#    container_name: logstash
#    environment:
#      - LS_JAVA_OPTS="-Xmx256m -Xms256m"   # Java 메모리 설정 (필요에 따라 조정)
#    ports:
#      - '5044:5044'  # Logstash 입력 포트 (필요에 따라 조정)
#    volumes:
#      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro  # Logstash 설정 파일
#      - ./logs:/var/log                                    # 로그 파일 경로
#    depends_on:
#      - elasticsearch
#    networks:
#      - app-tier

volumes:
  mysqldb-data:
    driver: local  # 로컬 드라이버 사용
#  elasticsearch-data:
#    driver: local  # 로컬 드라이버 사용

networks:
  app-tier:
    driver: bridge
