filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log  # 로그 파일 경로
    fields:
      environment: development  # 추가 필드 (환경 정보)
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]  # Elasticsearch 주소

setup.kibana:
  host: "http://kibana:5601"  # Kibana 주소

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
